spring:
  jackson:
    time-zone: Europe/Vienna
  datasource:
    url: jdbc:postgresql://localhost:5452/transaction_service_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true