version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5452:5432"
    volumes:
      - ./postgres/init/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
